In [42]:
import pandas as pd
import numpy as np
import os

In [43]:
# Data Chunking
NUM_SAMPLES_PER_MATRIX = 8
DATA_DIR = 'processed_data/'
def get_data_from_csv(path_csv, path_label):
    df = pd.read_csv(path_csv)
    df.drop(columns=['time'], inplace=True)
    X = [np.array(df.iloc[i:i+NUM_SAMPLES_PER_MATRIX]) for i in range(0, len(df) - NUM_SAMPLES_PER_MATRIX, NUM_SAMPLES_PER_MATRIX)]
    with open(path_label, 'r') as file:
        txt = file.read().strip()
        Y = [txt[int(i * len(txt)/len(X))] for i in range(0, len(X))]
    return X, Y

def get_data():
    dirs = os.listdir(DATA_DIR)
    print('len(dirs):', len(dirs))
    X, Y = [], []
    i = 0
    for dir in dirs:
        print(f'{i}/{len(dirs)}')
        files = os.listdir(os.path.join(DATA_DIR, dir))
        for file in files:
            if file.endswith('.csv'):
                X_file, Y_file = get_data_from_csv(os.path.join(DATA_DIR, dir, file), os.path.join(DATA_DIR, dir, file.replace('.csv', '_label.txt')))
                X.extend(X_file)
                Y.extend(Y_file)
        i += 1
    return X, Y
X, Y = get_data()
print(len(X))
print(X[0])
print(X[0].shape)
print(len(Y))

len(dirs): 24
0/24
1/24
2/24
3/24
4/24
5/24
6/24
7/24
8/24
9/24
10/24
11/24
12/24
13/24
14/24
15/24
16/24
17/24
18/24
19/24
20/24
21/24
22/24
23/24
172632
[[-0.65409213 -0.43702224 -0.18056355]
 [ 1.153561    2.32855797 -0.1830821 ]
 [-0.04868803 -0.76136452 -0.297876  ]
 [-0.83910161 -0.12955612  2.40312958]
 [-0.03190672 -0.83928841 -0.70131242]
 [ 1.11433256 -0.3332603  -0.05362078]
 [ 0.54784304 -0.37998322 -0.35502785]
 [ 0.09619431 -0.63261592 -0.43352789]]
(8, 3)
172632
